#!/bin/bash

LOG_DIR="./logs"
mkdir -p "$LOG_DIR"

DATASETS=("Strawberry" "PowerCons" "ECG200" "DistalPhalanxOutlineCorrect"  "Earthquakes")  #"GunPoint" "Strawberry" "PowerCons" "ECG200" "DistalPhalanxOutlineCorrect"  "Earthquakes" "Strawberry" "PowerCons" "ECG200" "DistalPhalanxOutlineCorrect"  "Earthquakes"

SIZE_PROTOTYPES=(1 2 3 5 10 20)

PROJECTION=True

REPEATS=(0 1 2 3 4)

for dataset in "${DATASETS[@]}"; do
    for size_prototype in "${SIZE_PROTOTYPES[@]}"; do

        for repeat in "${REPEATS[@]}"; do

            experiment_run="push_size${size_prototype}_${repeat}"
            GPU_ID=$repeat
            CUDA_VISIBLE_DEVICES="$GPU_ID" python3 main.py \
                --dataset "$dataset" \
                --projection "$PROJECTION" \
                --experiment_run "$experiment_run" \
                2>>"$LOG_DIR/error_$dataset.log" &

        done
        wait
        echo "Finished: dataset=$dataset, projection=$PROJECTION"

    done
done

echo "All experiments have been launched."